name: varlexenv
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - apispec=2.0.2=py_0
  - biopython=1.74=py37h01d97ff_0
  - bzip2=1.0.8=h01d97ff_1
  - ca-certificates=2019.9.11=hecc5488_0
  - certifi=2019.9.11=py37_0
  - curl=7.65.3=h22ea746_0
  - flask=1.1.1=py_0
  - flask-cors=3.0.8=py_0
  - htslib=1.9=h3a161e8_7
  - itsdangerous=1.1.0=py_0
  - jinja2=2.10.1=py_0
  - krb5=1.16.3=hcfa6398_1001
  - libblas=3.8.0=12_openblas
  - libcblas=3.8.0=12_openblas
  - libcurl=7.65.3=h16faf7d_0
  - libcxx=9.0.0=0
  - libcxxabi=9.0.0=0
  - libdeflate=1.0=h1de35cc_1
  - libedit=3.1.20170329=hcfe32e1_1001
  - libffi=3.2.1=h6de7cb9_1006
  - libgfortran=4.0.0=2
  - liblapack=3.8.0=12_openblas
  - libopenblas=0.3.7=h4bb4525_1
  - libssh2=1.8.2=hcdc9a53_2
  - llvm-openmp=9.0.0=h40edb58_0
  - markupsafe=1.1.1=py37h1de35cc_0
  - marshmallow=3.2.0=py_0
  - marshmallow-enum=1.5.1=py37_0
  - ncurses=6.1=h0a44026_1002
  - numpy=1.17.2=py37h6b0580a_0
  - openssl=1.1.1c=h01d97ff_0
  - pip=19.2.3=py37_0
  - python=3.7.3=h93065d6_1
  - pyyaml=5.1.2=py37h01d97ff_0
  - readline=8.0=hcfe32e1_0
  - setuptools=41.2.0=py37_0
  - sqlite=3.29.0=hb7d70f7_1
  - tabix=0.2.6=ha92aebf_0
  - tk=8.6.9=h2573ce8_1003
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h1de35cc_1001
  - yaml=0.1.7=h1de35cc_1001
  - zlib=1.2.11=h01d97ff_1006
  - pip:
    - apispec-webframeworks==0.4.0
    - appdirs==1.4.3
    - astroid==2.2.5
    - beautifulsoup4==4.8.0
    - biocommons-seqrepo==0.5.1
    - bioutils==0.5.0
    - bs4==0.0.1
    - chardet==3.0.4
    - click==7.0
    - coloredlogs==10.0
    - cssselect==1.0.3
    - fake-useragent==0.1.11
    - humanfriendly==4.18
    - idna==2.8
    - iniherit==0.3.9
    - isort==4.3.21
    - jedi==0.15.1
    - lazy-object-proxy==1.4.2
    - lxml==4.3.4
    - mccabe==0.6.1
    - parse==1.12.0
    - parso==0.5.1
    - pyee==6.0.0
    - pylint==2.3.1
    - pyppeteer==0.0.25
    - pyquery==1.4.0
    - pysam==0.15.2
    - requests==2.22.0
    - requests-html==0.10.0
    - seqrepo==0.0.0
    - six==1.12.0
    - soupsieve==1.9.2
    - text-unidecode==1.2
    - tqdm==4.32.2
    - typed-ast==1.4.0
    - urllib3==1.25.3
    - w3lib==1.20.0
    - websockets==8.0.1
    - wrapt==1.11.2
    - yoyo-migrations==6.1.0
prefix: /anaconda3/envs/varlexenv

